# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 003d9e77ab0ad0574c8498ac05b0faf05ed0d65c46e6a7d7d7a74a5d9deee6c599ed3875ef1d2fcf23c35524a4c9ad4dbe12b99e94e4e9303c167c7bede6c031

test:
  secret_key_base: a71229a842243084da2eb5edcdb342fc8d079af842fd0dc7ebecad5ab2f0bfc4069fdfa935a51db0697352013a026abbbf557cdb55c75f165b477ab6b42e9bdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
